---
title: "Untitled"
author: "Christine Brown"
date: "February 9, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

setwd("C:/Users/brown/Documents/Grad School/Fall 16/DDMII/lab 3")

library( maptools )
library( sp )
library(devtools)
library(dplyr)
devtools::install_github("hrecht/censusapi")
censuskey <- "5a1a01fa6496e71097aa2d4a066bed72117c8069"
library(censusapi)

unzip( "01-05-2015.zip" )
file.remove( "01-05-2015.zip" )

syr <- readShapePoly( fn="01-05-2015", proj4string=CRS( "+proj=longlat +datum=WGS84" ) )
plot( syr,  border="gray10" )

acs5_2015 <- getCensus(name="acs5", vintage=2015, key=censuskey, vars=c( "B22003_002E" , "B01001B_001E" , "B23025_005E" ) , region="tract:*" , regionin="state:36+county:067")
acs5_2015 <- rename(acs5_2015, Household.SNAP = B22003_002E )
acs5_2015 <- rename(acs5_2015, Black=B01001B_001E )
acs5_2015 <- rename(acs5_2015, Unemployed=B23025_005E )

color.function <- colorRampPalette( c("steel blue","light gray","firebrick4" ) )
col.ramp <- color.function( 5 ) # number of groups you desire
color.vector <- cut( rank(acs5_2015$Household.SNAP), breaks=5, labels=col.ramp )
color.vector <- as.character( color.vector )
syr$CensusTrac
head(acs5_2015)
head(syr)
acs5_2015$tract
